pipeline {
  agent {
    kubernetes {
      defaultContainer 'jnlp'
      yaml """
  apiVersion: v1
  kind: Pod
  spec:
    containers:
    - name: node
    image: node:16-alpine
    command:
    - cat
    tty: true
  """
    }
    }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
